name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install prerequisites
        run: |
          wf-pacman -S --noconfirm blocksds-ulibrary toolchain-gcc-arm-none-eabi-zlib toolchain-gcc-arm-none-eabi-libpng16

      - name: Build (Lua 5.2)
        run: make LUAVER=52

      - name: Build (Lua 5.3)
        run: make LUAVER=53

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Micro Lua DS
          path: |
            MicroLua*.nds
            CHANGELOG.md
            README.md
            doc/
            licenses/
            Fat/*/
